### ISSUE TITLE
brew-emp stop/start/restart commands restarting my Mac

### ISSUE THREAD

**Issue by mike-ngu** [mrded/brew-emp#10]
Hi!

I have a problem with my brew-emp server. 
when I'm trying to restart or stop brew-emp server it's restarting my computer...

I will be very appreciate for help or advice how can I solve this issue.

Thanks!

**Comment by mrded** [comment]
It's very strange =)

What version of OSx do you use?

**Comment by mike-ngu** [comment]
OS X EL Capitan
version 10.11
MacBook Air

**Comment by mrded** [comment]
What does `brew doctor` say?

**Comment by mike-ngu** [comment]
brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  mysql

Warning: Homebrew's sbin was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting the PATH for example like so
  echo 'export PATH="/usr/local/sbin:$PATH"' >> ~/.bash_profile

**Comment by mike-ngu** [comment]
I can see my local web sites and except this restarting issue everything works fine

**Comment by mrded** [comment]
Look at `/usr/local/bin/brew-emp` file, and try to run commands separately. Find the command that reboots your computer.

**Comment by mike-ngu** [comment]
I've ran commands separately..
for instance: 
brew-emp stop 
brew-emp restart

**Comment by mike-ngu** [comment]
and this is what I have in the brew-emp file:


#!/bin/bash

case "$1" in
"start")
  sudo brew services start nginx
  sudo brew services start php56
  sudo brew services start redis
  sudo brew services start memcached
  ;;
"stop")
  sudo brew services stop nginx
  sudo brew services stop php56
  sudo brew services stop redis
  sudo brew services stop memcached
  ;;
"restart")
  sudo brew services restart nginx
  sudo brew services restart php56
  sudo brew services restart redis
  sudo brew services restart memcached
  ;;
*)
  echo 'Usage: brew-emp [start | stop | restart]'
  ;;
esac

**Comment by mrded** [comment]
That's right, in that file you can see what does script run to restart a server. 

Try to run  this separately:

```
sudo brew services restart nginx
sudo brew services restart php56
sudo brew services restart redis
sudo brew services restart memcached
```

What command restarts your computer?

**Comment by mike-ngu** [comment]
well, these two commands rebooting my computer:
```
sudo brew services restart nginx
sudo brew services restart redis
```
This is what I've got when I'm trying restart php56, but I have previously installed php71 in my system before I installed brew-emp... so php -v in terminal shows me php version 7.1

```
sudo brew services restart php56
Error: Formula `php56` is not installed.
```

and the same error I've got when I ran restart memcached

```
sudo brew services restart memcached
Error: Formula `memcached` is not installed.
```

**Comment by mrded** [comment]
Update the script then to `php71` and remove `memcached` if you don't use it.

If you run just `sudo brew services restart nginx` does it reboot you computer?

**Comment by mike-ngu** [comment]
yes, if run just `sudo brew services restart nginx` or  `sudo brew services restart redis` it's rebooting my system
and I will need `memcached ` I just didn't get to this step yet, at first I want to solve this rebooting issue

wait, it's very very strange...
when I've just ran this command to update my php version it's as well reboots my computer

`curl -L https://raw.github.com/mrded/brew-emp/master/tools/update.sh | bash`

damn, what's the hell is going on with my mac?!))

**Comment by mrded** [comment]
Something wrong is going with `brew services` or with `nginx` and `redis` on you computer. Try to runs services without using `brew services`. Like so:

Run:
`sudo nginx &`
`redis-server &`

Stop:
`sudo nginx -s stop`
`pkill redis-server`

Let me know, if these commands are also reloading you mac.

**Comment by ogrrd** [comment]
@mike-ngu when your machine comes back, do you see a message about your machine being rebooted due to a problem? Just wondering if you're seeing kernel panics (this spontaneous reboot being the result).

**Comment by mike-ngu** [comment]
`sudo nginx`/ `sudo nginx -s stop` and `redis-server` / `pkill redis-server `works fine and it's don't rebooting the system. In this way I can run and stop them without any issues 

**@ogrrd**
No, I don't see any kernel error messages and it's just rebooting system and relaunch applications which were opened. pretty usual

**Comment by mrded** [comment]
@mike-ngu if it works - update your `/usr/local/bin/brew-emp` file to use these commands rather than brew services.

**Comment by mike-ngu** [comment]
when I run these commands to `stop` / `restart` php71 I'm getting the same result...reboot
`sudo brew services restart php71`
`sudo brew services stop php71`

maybe I have a problem with my brew package manager, and I need to delete it and install again?
what do you think?

**Comment by mrded** [comment]
Yes, I think so. Try to reinstall it. Or even better, come and ask `brew` community about your problem. For me, it looks like the problem is in general with all brew services.

**Comment by mike-ngu** [comment]
yes, I think so.

**@mrded** Thank you very much for your time and help!

**Comment by mrded** [comment]
@mike-ngu you are very welcome :)
