### ISSUE TITLE
nginx: [emerg] open() "/usr/local/var/log/nginx" failed (21: Is a directory)

### ISSUE THREAD

**Issue by mrded** [mrded/brew-emp#3]
```
$ sudo nginx
nginx: [emerg] open() "/usr/local/var/log/nginx" failed (21: Is a directory)
```

**Comment by yanfeng1012** [comment]
I start nginx ,then i get this errow plz can you help me to fix this error
nginx: [alert] could not open error log file: open() "/usr/local/var/log/nginx/error.log" failed (13: Permission denied)

**Comment by mrded** [comment]
@yanfeng1012 you need to give `/usr/local/var/log/nginx/` folder permissions, so nginx can write into it.
